<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/images/favicon.svg" type="image/svg+xml" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.5.1/styles/github.min.css" />
    <meta http-equiv="content-security-policy" content=""><title>jediとかvirtualenvとかがReason: image not foundと言ってぶっ壊れたときの対処 - 2016-08-26 | 葉月夜堂</title><link href="https://twitter.com/p_km" rel="me" data-svelte="svelte-10crdf0">
    <link rel="webmention" href="https://webmention.io/sveltekit-prerender/webmention" data-svelte="svelte-10crdf0">
    <link rel="pingback" href="https://webmention.io/sveltekit-prerender/xmlrpc" data-svelte="svelte-10crdf0"><meta property="og:type" content="article" data-svelte="svelte-6t30ru"><meta property="og:title" content="jediとかvirtualenvとかがReason: image not foundと言ってぶっ壊れたときの対処 - 2016-08-26 | 葉月夜堂" data-svelte="svelte-6t30ru"><meta property="og:description" content="ある日突然jedi（EmacsでPythonを書くときにつかうすごいやつだよ）がぶっ壊れた。python-modeのバッファでピリオドを打つたびにError (jedi): Failed to start Jedi EPC server. *** You may need to run &amp;quot;M-x jedi:install-server&amp;quot;. ***This could solve the problem especially if you haven&amp;#39;t run the command yet since Jedi.el installation or update and if the server complains about Python module imports. というメッセージが出てくるし、当然補完機能は使えない。指示通りコマンドを実行しても何も起きない。よくみると*Messages*にServer may raise an error. Use &amp;quot;M-x epc:pop-to-last-server-process-buffer RET&amp;quot; to" data-svelte="svelte-6t30ru"><meta property="og:site_name" content="葉月夜堂" data-svelte="svelte-6t30ru"><meta property="og:image" content="http://sveltekit-prerender/images/favicon.svg" data-svelte="svelte-6t30ru">
	<link rel="stylesheet" href="/_app/immutable/assets/pages/__layout.svelte-f9a44566.css">
	<link rel="stylesheet" href="/_app/immutable/assets/time.svelte_svelte_type_style_lang-61ea3f89.css">
	<link rel="stylesheet" href="/_app/immutable/assets/pages/_...entity_.svelte-d69f21a9.css">
	<link rel="modulepreload" href="/_app/immutable/start-0007c59c.js">
	<link rel="modulepreload" href="/_app/immutable/chunks/index-7416df8b.js">
	<link rel="modulepreload" href="/_app/immutable/chunks/singletons-d1fb5791.js">
	<link rel="modulepreload" href="/_app/immutable/pages/__layout.svelte-0c722760.js">
	<link rel="modulepreload" href="/_app/immutable/chunks/time.svelte_svelte_type_style_lang-2ab901cd.js">
	<link rel="modulepreload" href="/_app/immutable/pages/_...entity_.svelte-8f381217.js">
	<link rel="modulepreload" href="/_app/immutable/chunks/tags-06b98af7.js">
  </head>
  <body>
    <div>




<nav><ul><li><a sveltekit:prefetch href="/">葉月夜堂</a>
      </li><li><a sveltekit:prefetch href="/about">about</a>
      </li></ul></nav>



<div class="nav-background svelte-6mvvsp isHeaderInView" style=""></div>

<main><article data-kind="note" class="svelte-6mvvsp"><header class="svelte-6mvvsp"><h1 class="svelte-6mvvsp">jediとか<wbr>virtualenvと<wbr>かが<wbr>Reason: <wbr>image <wbr>not <wbr>foundと<wbr>言って<wbr>ぶっ壊れた<wbr>ときの<wbr>対処</h1>

      

      <section class="meta svelte-6mvvsp"><p class="svelte-6mvvsp"><time title="6 年前" class="svelte-5ni4x2">Fri Aug 26 2016 00:17:53 GMT+0000 (Coordinated Universal Time)</time></p>

        <p class="svelte-6mvvsp"><a href="https://github.com/kissge/yo.eki.do/commits/master/notes/jedi-virtualenv.md" title="Sun Apr 17 2022 12:08:43 GMT+0000 (Coordinated Universal Time)" class="svelte-6mvvsp">最終更新：3 か月前</a></p></section>

      

      

      <section class="header-image svelte-6mvvsp" style=""></section></header>

    <section class="body svelte-6mvvsp"><!-- HTML_TAG_START --><p>ある日突然jedi（EmacsでPythonを書くときにつかうすごいやつだよ）がぶっ壊れた。
python-modeのバッファでピリオドを打つたびに</p>
<pre><code>Error (jedi): Failed to start Jedi EPC server.
*** You may need to run &quot;M-x jedi:install-server&quot;. ***
This could solve the problem especially if you haven&#39;t run the command yet
since Jedi.el installation or update and if the server complains about
Python module imports.
</code></pre>
<p>というメッセージが出てくるし、当然補完機能は使えない。
指示通りコマンドを実行しても何も起きない。</p>
<!--more-->

<p>よくみると*Messages*に</p>
<pre><code>Server may raise an error. Use &quot;M-x epc:pop-to-last-server-process-buffer RET&quot; to see full traceback:
</code></pre>
<p>とあるのでtracebackを見てみると</p>
<pre><code>dyld: Library not loaded: *****
  Referenced from: *****:
  Reason: image not found
</code></pre>
<p>という見慣れないエラーがある。なんだこれ。</p>
<h3 id="原因">原因</h3>
<p>簡単に言うとvirtualenvが壊れていた。
私の環境では <code>(custom-set-variables &#39;(jedi:environment-root &quot;jedi&quot;))</code> という<a href="https://github.com/kissge/.emacs.d/blob/master/inits/15-python.el#L8">感じ</a>でvirtualenvを使う設定になっているのだが、そのディレクトリの中にある大量のシンボリックリンクがいずれもリンク切れになっていた。
homebrewでPythonをバージョンアップしたためである。</p>
<p>と、いうわけで、このディレクトリを削除して作りなおすと万事うまくいった。よかった。</p>
<p>あんまし関係無いけど、この問題に対処する隙がない間エラーを無視してとりあえずjediを <code>el-get-remove</code> しようとしたら <code>auto-complete</code> がないから無理〜と言って怒られたのは納得がいかない。
jediさん何とかして。</p>
<!-- HTML_TAG_END --></section>

    

    <section class="mentions svelte-19gm1ik"><section class="reaction svelte-19gm1ik"><a href="https://twitter.com/intent/tweet?url=" class="svelte-19gm1ik" style="background-image: url(/_app/immutable/assets/message-circle-c0b45d48.svg); color: #3579d1;"><small class="svelte-19gm1ik">Twitterで</small>
        <span class="svelte-19gm1ik">コメントする</span></a></section>

  <h1 class="svelte-19gm1ik">Mentions</h1>
  <ol reversed class="svelte-19gm1ik loading"></ol>
</section></article>
</main>

<footer>Built with <a href="https://github.com/kissge/monolog">monolog</a>
</footer>


		<script type="module" data-sveltekit-hydrate="zmmvy">
		import { start } from "/_app/immutable/start-0007c59c.js";
		start({
			target: document.querySelector('[data-sveltekit-hydrate="zmmvy"]').parentNode,
			paths: {"base":"","assets":""},
			session: {},
			route: true,
			spa: false,
			trailing_slash: "always",
			hydrate: {
				status: 200,
				error: null,
				nodes: [0, 2],
				params: {entity:"notes\u002Fjedi-virtualenv\u002F"},
				routeId: "[...entity]"
			}
		});
	</script><script type="application/json" sveltekit:data-type="props">{"entity":{"name":"jediとかvirtualenvとかがReason: image not foundと言ってぶっ壊れたときの対処","nameSegmented":["jediとか","virtualenvと","かが","Reason: ","image ","not ","foundと","言って","ぶっ壊れた","ときの","対処"],"kind":"note","urlPath":"/notes/jedi-virtualenv","historyURL":"https://github.com/kissge/yo.eki.do/commits/master/notes/jedi-virtualenv.md","lastModified":"2022-04-17T12:08:43.000Z","attributes":{"from":"wordpress","title":"jediとかvirtualenvとかがReason: image not foundと言ってぶっ壊れたときの対処","date":"2016-08-26T00:17:53.000Z"},"tags":[],"body":"\u003Cp>ある日突然jedi（EmacsでPythonを書くときにつかうすごいやつだよ）がぶっ壊れた。\npython-modeのバッファでピリオドを打つたびに\u003C/p>\n\u003Cpre>\u003Ccode>Error (jedi): Failed to start Jedi EPC server.\n*** You may need to run &quot;M-x jedi:install-server&quot;. ***\nThis could solve the problem especially if you haven&#39;t run the command yet\nsince Jedi.el installation or update and if the server complains about\nPython module imports.\n\u003C/code>\u003C/pre>\n\u003Cp>というメッセージが出てくるし、当然補完機能は使えない。\n指示通りコマンドを実行しても何も起きない。\u003C/p>\n\u003C!--more-->\n\n\u003Cp>よくみると*Messages*に\u003C/p>\n\u003Cpre>\u003Ccode>Server may raise an error. Use &quot;M-x epc:pop-to-last-server-process-buffer RET&quot; to see full traceback:\n\u003C/code>\u003C/pre>\n\u003Cp>とあるのでtracebackを見てみると\u003C/p>\n\u003Cpre>\u003Ccode>dyld: Library not loaded: *****\n  Referenced from: *****:\n  Reason: image not found\n\u003C/code>\u003C/pre>\n\u003Cp>という見慣れないエラーがある。なんだこれ。\u003C/p>\n\u003Ch3 id=\"原因\">原因\u003C/h3>\n\u003Cp>簡単に言うとvirtualenvが壊れていた。\n私の環境では \u003Ccode>(custom-set-variables &#39;(jedi:environment-root &quot;jedi&quot;))\u003C/code> という\u003Ca href=\"https://github.com/kissge/.emacs.d/blob/master/inits/15-python.el#L8\">感じ\u003C/a>でvirtualenvを使う設定になっているのだが、そのディレクトリの中にある大量のシンボリックリンクがいずれもリンク切れになっていた。\nhomebrewでPythonをバージョンアップしたためである。\u003C/p>\n\u003Cp>と、いうわけで、このディレクトリを削除して作りなおすと万事うまくいった。よかった。\u003C/p>\n\u003Cp>あんまし関係無いけど、この問題に対処する隙がない間エラーを無視してとりあえずjediを \u003Ccode>el-get-remove\u003C/code> しようとしたら \u003Ccode>auto-complete\u003C/code> がないから無理〜と言って怒られたのは納得がいかない。\njediさん何とかして。\u003C/p>\n","headline":"ある日突然jedi（EmacsでPythonを書くときにつかうすごいやつだよ）がぶっ壊れた。python-modeのバッファでピリオドを打つたびにError (jedi): Failed to start Jedi EPC server. *** You may need to run &quot;M-x jedi:install-server&quot;. ***This could solve the problem especially if you haven&#39;t run the command yet since Jedi.el installation or update and if the server complains about Python module imports. というメッセージが出てくるし、当然補完機能は使えない。指示通りコマンドを実行しても何も起きない。よくみると*Messages*にServer may raise an error. Use &quot;M-x epc:pop-to-last-server-process-buffer RET&quot; to","links":{"to":{"urlPath":"/notes/jedi-virtualenv","entities":[]},"from":{"urlPath":"/notes/jedi-virtualenv","entities":[]},"kind":{"urlPath":"/notes/jedi-virtualenv","entities":[]}}}}</script></div>
  </body>
</html>
